title: Tao Bojlén
baseurl: "/" # the subpath of your site, e.g. /blog
description: Tao Bojlén's blog and portfolio.
tagline: Tao Bojlén's blog and portfolio.
url: "https://www.btao.org"

collections:
  projects:
    output: false

# Auto-adds trailing slash
permalink: pretty

# Theme settings
header_pages:
  - index.md
  - portfolio.html
  - contact.html

# Build settings
kramdown:
  hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-seo-tag

defaults:
  -
    scope:
      path:            "_projects/*.md"
    values:
      sitemap:         false

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - .git
  - .gitignore

include:
  - _redirects