# top level stuff you probably don't need to touch
highlighter: pygments
url: "http://btao.org"
sitetitle: "btao.org"
markdown: kramdown
rdiscount:
  extensions: [smart]
paginate: 5
collections:
  notes:
    output: true
    permalink: /notes/:title.html
exclude: [README.md]
plugins:
  - jekyll-paginate
  - jekyll-sitemap
